blogs/urls.py
from django.urls import path

from blogs import views


app_name = 'blogs'
urlpatterns = [
    path('', views.blog_home, name='blog-home')
]

contact/urls.py
from django.urls import path

from contact import views

urlpatterns = [
    path('', views.contact, name='contact')
]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.landing, name='home'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contact/', include('contact.urls'), name='contact'),
    path('users/', include('usersapp.urls'), name='users'),
    path('blogs/', include('blogs.urls'), name='blogs'),
    path('projects/', include('projects.urls'), name='projects'),
    path('my-profile/', include('myprofile.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myprofile/urls.py
from django.urls import path

from myprofile import views

urlpatterns = [
    path('', views.my_profile, name='my-profile')
]

projects/urls.py
from django.urls import path

from projects import views


app_name = 'projects'
urlpatterns = [
    path('', views.projects_home, name='projects-home'),
    path('create_project/', views.create_project, name='create-project')
]

usersapp/urls.py
from django.urls import path

from usersapp import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

blogs/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    category = models.CharField(max_length=200, null=False)
    posted_on = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, null=False)
    title = models.CharField(max_length=500, null=False)
    text = models.TextField(null=False)

    def __str__(self):
        return self.title

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

myprofile/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=200, null=False)
    description = models.TextField()
    img = models.ImageField(upload_to='pics/projects')

    def __str__(self):
        return self.title

usersapp/models.py
from django.db import models

# Create your models here.

usersapp/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

blogs/views.py
from django.shortcuts import render
from .models import Blog

# Create your views here.


def blog_home(request):
    context = {}

    blogs = Blog.objects.all()
    context['blogs'] = blogs
    return render(request, 'blogs/blog-home.html', context)

contact/views.py
from django.shortcuts import render

# Create your views here.


def contact(request):

    if request.method == 'POST':
        print(request.POST['name'])
    return render(request, 'contact/contact-us.html')

home/views.py
from django.shortcuts import render

# Create your views here.


def landing(request):
    return render(request, 'home/index.html')

myprofile/views.py
from django.shortcuts import render

# Create your views here.


def my_profile(request):
    return render(request, 'my-profile/profile-home.html')

projects/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib.auth.models import User, auth
from .models import Project

# Create your views here.


def projects_home(request):
    context = {}
    projects = Project.objects.all()
    context['projects'] = projects
    return render(request, 'projects/projects-home.html', context)


@login_required (login_url='users/login/')
def create_project(request):
    context = {}
    if request.method == 'POST':
        if auth.user.email == 'praveenraghav04@gmail.com':
            title = request.POST['title']
            description = request.POST['description']

            project = Project.objects.create(title=title, description=description)
            project.save()
            context = {"message": "Project added Successfully"}
            return render(request, 'projects/added.html', context)
        else:
            context = {"message": "You are not allowed to add Project"}
            return render(request, 'projects/create-project.html', context)




    else:
        return render(request, 'projects/create-project.html')

usersapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages

# Create your views here.


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        if User.objects.filter(username=username).exists():
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('home')
            else:
                messages.error(request, "Oops..Wrong Password!!")
                return redirect('users:login')
        else:
            messages.error(request, "Email not found..Use another or Register..")
            return redirect('users:login')

    else:
        return render(request, 'users/login.html')


def signup(request):
    context = {}
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if User.objects.filter(username=email).exists():
            messages.error(request, 'Dear ' + first_name + '!, I think you are registered already..Can you please'
                                                           ' try Login!!')
            return redirect('users:signup')
        user = User.objects.create_user(username=email, first_name=first_name, last_name=last_name, email=email,
                                        password=password1)
        user.save()
        messages.success(request, 'Welcome ' + first_name + '..Go ahead to Login!!')
        return redirect('users:login')
    else:
        return render(request, 'users/register.html', context)


@login_required(login_url='/users/login/')
def logout(request):
    auth.logout(request)
    messages.success(request, 'You have logged out successfully')
    return redirect('users:login')

templates/blogs/blog-home.html
{% extends 'home/base.html' %}

{% block content %}
  <section class="text-gray-700 body-font overflow-hidden">
  <h6 style="text-align: center; font-size: 15pt; color: white; background-color: #79aec8; width: 83%; margin: auto; border-radius: 8px;padding: 0.5%">Blog Posts</h6>

  <div class="container px-5 py-12 mx-auto">
    <div class="-my-8">
      {% for blog in blogs %}
      <div class="py-8 flex border-t-2 border-gray-200 flex-wrap md:flex-no-wrap">
        <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
          <span class="tracking-widest font-medium title-font text-blue-800">{{ blog.category }}</span>
          <span class="mt-1 text-blue-500 text-sm">{{ blog.posted_on }}</span>
          <span class="mt-1 text-blue-500 text-sm">Posted By: {{ blog.author }}</span>
        </div>
        <div class="md:flex-grow">
          <h2 class="text-2xl font-medium text-gray-900 title-font mb-2">{{ blog.title}}</h2>
          <p class="leading-relaxed">{{ blog.text }}</p>
          <a class="text-teal-500 inline-flex items-center mt-4">Learn More
            <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path d="M5 12h14"></path>
              <path d="M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>


{% endblock %}

templates/contact/contact-us.html
{% extends 'home/base.html' %}

{% block content%}
    <h6 style="text-align: center; font-size: 15pt; color: white; background-color: #79aec8; width: 83%; margin: auto; border-radius: 8px;padding: 0.5%">Contact Me</h6>

    <section class="text-gray-700 body-font">

      <div class="container px-3" style="width: 100%;margin: auto;padding-top: 40px; padding-bottom: 40px">

        <div class=" md:w-full bg-gray-300 rounded-lg overflow-hidden p-10 flex justify-start relative " style="width: 100%;">
          <iframe width="100%" height="100%" class="absolute inset-0" frameborder="0" title="map" marginheight="0" marginwidth="0" scrolling="no" src="https://maps.google.com/maps?width=100%&height=600&hl=en&q=%iiit+allahabad&ie=UTF8&t=&z=14&iwloc=B&output=embed"></iframe>
          <div class="bg-white relative flex flex-wrap py-6 " style="margin: auto" >
            <div class="lg:w-full px-6 ">
              <h2 class="title-font font-medium text-blue-600 tracking-widest text-sm">ADDRESS</h2>
              <p class="leading-relaxed text-blue-700" >Department of Information Technology,<br> Indian Institute of Information Technology,<br>
                  Devghat, Jhalwa, Prayagraj (Uttar Pradesh)<br>211015</p>
            </div>
            <div class="lg:w-full px-6 mt-4 lg:mt-0">
                <br>
              <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm">EMAIL</h2>
              <a class="text-teal-500 leading-relaxed">mit2019097@iiita.ac.in</a><br>
              <a class="text-teal-500 leading-relaxed">praveenraghav@gmail.com</a>
              <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mt-4">PHONE</h2>
              <p class="leading-relaxed">+91-8273367349</p>
              <p class="leading-relaxed">+91-7906049098</p>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

templates/home/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="icon" href="../../static/pr.jpg">
        <title>Raghav's</title>
    </head>

    <body>

        {% include 'home/header.html' %}
        <!--hr style="height:2px;color:gray;background-color:#79aec8; width: 82%;margin: auto;"><br-->
        {% block content %}
        {% endblock %}
        <hr style="height:2px;color:gray;background-color:#79aec8; width: 82%;margin: auto;">
        {% include "home/footer.html" %}
        <hr style="height:2px;color:gray;background-color:#79aec8; width: 82%;margin: auto;"><br>
    </body>
</html>

templates/home/body.html
<section class="text-gray-700 body-font">
          <div style="margin: auto; width: 82.5%"><marquee><p style="color: darkred">WELCOME TO PRAVEENRAGHAV.IN<p></p></marquee></div>

  <div class="container px-5 py-5 mx-auto flex flex-wrap">
    <div class="lg:w-1/2 w-full mb-10 lg:mb-0 rounded-lg overflow-hidden">
      <img alt="feature" class="object-cover object-center h-full w-full" src="../../static/raghav1.jpg">
    </div>
    <div class="flex flex-col flex-wrap lg:py-6 -mb-10 lg:w-1/2 lg:pl-12 lg:text-left text-center">
      <div class="flex flex-col mb-10 lg:items-start items-center">
        <div class="w-12 h-12 inline-flex items-center justify-center rounded-full bg-teal-100 text-teal-500 mb-5">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
              <img src="../../static/raghav.jpg" style="border-radius: 50%">
          </svg>
        </div>
        <div class="flex-grow">
          <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Welcome Dear</h2>
          <p class="leading-relaxed text-base text-blue-600">
              Hi! I am Praveen Raghav. Currently I am in Masters of Technology(M.Tech) in IT from Indian Institute of Information Technology, Allahabad (Prayagraj).
              I have joined M.Tech in August 2019. <br>
              Love to travel a lot, but due to Covid-19, spent last one year in a 10x10 room, don't know how,
              but obviously with my Lappy and Fibre connection :).<br>
              My hobbies are Cooking..Sports Shooting..watching Animation Movies. Always passionate to learn new things, be it
              Hypnosis, Dowsing, Reiki, Yoga or How to experiment with a new Dish ;)..<br><br>
              If you have something to say...Just <a href="{% url 'contact' %}">click here..</a>
          </p>
        </div>
      </div>
      <!--div class="flex flex-col mb-10 lg:items-start items-center">
        <div class="flex-grow">
          <h2 class="text-gray-900 text-lg title-font font-medium mb-3">About Me</h2>
          <p class="text-blue-600">

          </p>
        </div>
      </div!-->
      <div class="flex flex-col mb-10 lg:items-start items-center">
        <div class="w-12 h-12 inline-flex items-center justify-center rounded-full bg-teal-100 text-teal-500 mb-5">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
            <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
            <circle cx="12" cy="7" r="4"></circle>
          </svg>
        </div>
        <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Connect me on:</h2>
            <p class="leading-relaxed text-base"></p>
            <a href="https://www.linkedin.com/in/praveen-k-raghav-139649a1/" style="color: #003366" target="_blank">LinkedIn</a> &nbsp;
            <a href="https://github.com/praveenraghav97" style="color: #003366" target="_blank">GitHub</a>&nbsp;
            <a href="https://hack.codingblocks.com/app/users/266098" target="_blank" style="color: #003366">HackerBlocks</a>&nbsp;
        </div>
      </div>
    </div>
  </div>
</section>

templates/home/footer.html
<footer class="text-gray-700 body-font">
  <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900" href="{% url 'home' %}">
        <span class="ml-3 text-l" style="background-color:#609ab6;color: white; padding: 5%;margin: auto;border-radius: 8px">PraveenRaghav.Com</span>
    </a>
    <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4" style="margin: auto">© 2020 Praveen Raghav —
      <a class="text-gray-600 ml-1" rel="noopener noreferrer" target="_blank">Designed and Developed by Praveen K Raghav</a>
    </p>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <a class="text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
          <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
          <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
          <circle cx="4" cy="4" r="2" stroke="none"></circle>
        </svg>
      </a>
    </span>
  </div>
</footer>

templates/home/header.html
<header class="text-gray-700 body-font">
  <div class="container mx-auto flex flex-wrap shadow-lg rounded flex-col md:flex-row items-center mb-6" style="width: 83%; border-radius: 5px;">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" href=  {% url 'home' %}>
      <div class="w-20 h-20 inline-flex items-center justify-center rounded-full ml-5">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
              <img src="../../static/pr.jpg" style="border-radius: 50%">
          </svg>
        </div></a>
    {% if user.is_authenticated %}
    <span style="margin: auto">Namaste {{ user.first_name }} _/\_</span>
    {% endif %}
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a class="mr-5 hover:text-gray-900" href= {% url 'home' %}>Home</a>
      <!--a class="mr-5 hover:text-gray-900" href={% url 'blogs:blog-home' %}>My Blog</--a!-->
      <a class="mr-5 hover:text-gray-900" href="{% url 'projects:projects-home' %}">Projects</a>
      <a class="mr-5 hover:text-gray-900" href="{% url 'my-profile' %}">Edu. Background</a>
      <a class="mr-5 hover:text-gray-900" href="{% url 'contact' %}">Contact Me</a>
    </nav>
    {% if user.is_authenticated %}
        <button class="inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">
            <a href="{% url 'users:logout' %}">Logout</a>
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </button>
    {% else %}
        <button class="inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">
            <a href="{% url 'users:login' %}">Login/Join</a>
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </button>
    {% endif %}
  </div>
</header>

templates/home/index.html
{% extends 'home/base.html' %}

{% block content %}
    {% include 'home/body.html' %}
{% endblock %}

templates/my-profile/profile-home.html
{% extends 'home/base.html' %}

{% block content %}
    <h6 style="text-align: center; font-size: 15pt; color: white; background-color: #79aec8; width: 83%; margin: auto;
     border-radius: 8px;padding: 0.5%">Educational Background</h6>
    <section class="text-gray-700 body-font">
      <div class="container px-5 py-12 mx-auto">
        <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-200 sm:flex-row flex-col">
          <div class="sm:w-32 sm:h-32 h-20 w-20 sm:mr-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="sm:w-16 sm:h-16 w-10 h-10" viewBox="0 0 24 24">
              <img src="../../static/pg.png" style="border-radius: 50%">
            </svg>
          </div>
          <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
            <h2 class="text-blue-600 text-lg title-font font-medium mb-2">Post Graduation: M.Tech</h2>
            <h2 class="text-blue-400 text-md title-font font-medium mb-2">Specialization: Information Technology</h2>
            <p class="text-blue-400 text-md title-font font-medium mb-2">Indian Institute of Information Technology, Allahabad - U.P.</p>
            <p class="mt-3 text-blue-400 inline-flex items-center">Passing Year : 2019 - 2021 (CGPA: 8.81)</p>
          </div>
        </div>
        <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-5 border-gray-200 sm:flex-row flex-col">
          <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
            <h2 class="text-blue-600 text-lg title-font font-medium mb-2">Under Graduation: B.Tech</h2>
            <h2 class="text-blue-400 text-md title-font font-medium mb-2">Specialization: Information Technology</h2>
            <p class="text-blue-400 text-md title-font font-medium mb-2">Meerut Institute of Engineering and Technology, Meerut - U.P. (Affiliated to - Dr. APJ Abdul Kalam Technical University, Lucknow)</p>
            <p class="mt-3 text-blue-400 inline-flex items-center">Passing Year : 2013 - 2017 (Percentage: 81.30%)</p>
          </div>

          <div class="sm:w-32 sm:order-none order-first sm:h-32 h-20 w-20 sm:ml-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="sm:w-16 sm:h-16 w-10 h-10" viewBox="0 0 24 24">
              <circle cx="6" cy="6" r="3"></circle>
              <circle cx="6" cy="18" r="3"></circle>
              <img src="../../static/ug.png" style="border-radius: 50%">
            </svg>
          </div>
        </div>

        <div class="container px-5 py-5 mx-auto">
        <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-200 sm:flex-row flex-col">
          <div class="sm:w-32 sm:h-32 h-20 w-20 sm:mr-10 inline-flex items-center justify-center rounded-full text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="sm:w-16 sm:h-16 w-10 h-10" viewBox="0 0 24 24">
               <img src="../../static/12jpg.jpg">
            </svg>
          </div>
          <div class="flex-grow sm:text-left text-center mt-2 sm:mt-0">
            <h2 class="text-blue-600 text-lg title-font font-medium mb-2">Senior Secondary Certificate - 12th</h2>
            <p class="text-blue-400 text-md title-font font-medium mb-2">G.D. Public School (Affiliated to - CBSE, New Delhi)</p>
            <p class="mt-3 text-blue-400 inline-flex items-center">Passing Year : 2011 - 2012 (Percentage: 77.20%)</p>
          </div>
        </div>
        <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-200 sm:flex-row flex-col">
          <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
            <h2 class="text-blue-600 text-lg title-font font-medium mb-2">Higher Secondary Certificate - 10th</h2>
            <p class="text-blue-400 text-md title-font font-medium mb-2">SRD Higher Secondary School, Sidhpur (Affiliated to - Uttar Pradesh State Board, Allahabad)</p>
            <p class="mt-3 text-blue-400 inline-flex items-center">Passing Year : 2008 - 2009 (Percentage: 76.50%)</p>
          </div>
          <div class="sm:w-32 sm:order-none order-first sm:h-32 h-20 w-20 sm:ml-10 inline-flex items-center justify-center rounded-full text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="sm:w-16 sm:h-16 w-10 h-10" viewBox="0 0 24 24">
              <circle cx="6" cy="6" r="3"></circle>
              <circle cx="6" cy="18" r="3"></circle>
              <img src="../../static/10jpg.jpg">
            </svg>
          </div>
        </div>
        </div>
        </div>
    </section>

{% endblock %}

templates/projects/added.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Project added</h1>

</body>
</html>

templates/projects/create-project.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="container sm:w-auto md:w-1/2 lg:w-1/3 xl:w-1/4" style="margin: auto">
      <h5 style="margin: auto">{{ message }}</h5>
      <form class="bg-gray-200 shadow-md rounded px-8 pt-6 pb-8 mb-4" method="post" action={% url 'projects:create-project' %}>
      {% csrf_token %}
          <h2 class="mb-8" style="text-align: center;color: #79aec8;font-size: 20pt;">Add Project</h2>
            {% for message in messages %}
                 <div class="mb-6">
                    <p style="text-align: center;color: {% if message.tags == 'success' %}green {% else %}red{% endif %}">{{ message }}</p>
                 </div>
            {% endfor %}
        <div class="mb-8">
          <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none hover:shadow-outline focus:shadow-outline" name="title" id="title" type="text" placeholder="Title of Project" required>
        </div>
        <div class="mb-8">
          <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none hover:shadow-outline focus:shadow-outline" id="description" name="description" type="textarea" rows="6" placeholder="Description of Project" required>
        </div>
        <div class="flex items-center justify-between">
          <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Add Project
          </button>
        </div>
        <br>

      </form>
    </div>


{% endblock %}

templates/projects/projects-home.html
{% extends 'home/base.html' %}


{% block content %}
    <section class="text-gray-700 body-font">
      <h6 style="margin:auto;text-align: center; font-size: 15pt; color: white; background-color: #79aec8; width: 83%; margin: auto; border-radius: 8px;padding: 0.5%">My Personal projects</h6>
      <div class="container px-5 py-8 mx-auto">
{#        <div class="flex flex-wrap w-full mb-20">#}
{#          <div class="lg:w-1/2 w-full mb-6 lg:mb-0">#}
{#            <h1 class="sm:text-l text-l font-medium mb-4 text-gray-600">My Personal projects :</h1>#}
{#            <div class="h-1 w-80 bg-blue-200 rounded"></div>#}
{#          </div>#}
{#          </div>#}
        <div class="flex flex-wrap -m-4">
          {% for project in projects %}
              <div class="xl:w-1/2 md:w-1/2 p-4">
                <div class="bg-gray-100 p-6 rounded-lg">
                  <img class="h-64 rounded w-full object-fill object-center mb-6" src="../../static/timeseries.png" alt="img"
                       style="border: 1px #cc1111;">
                  <h3 class="tracking-widest text-teal-500 text-xs font-medium title-font">Project Title</h3>
                  <h2 class="text-lg text-gray-900 font-medium title-font mb-4">{{ project.title }}</h2>
                  <h3 class="tracking-widest text-teal-500 text-xs font-medium title-font">Description of Project</h3>
                  <p class="leading-relaxed text-base">{{ project.description }}</p>
                </div>
              </div>
          {% endfor %}
        </div>
      </div>
    </section>
{% endblock %}